version: "3"

services:
  app:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - UVICORN_OPTS='--reload'
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - ..:/app
  redis:
    image: redis:6.2
    expose:
      - 6379
